### ISSUE TITLE
Starting Database

### ISSUE THREAD

**Issue by phionabrie** [alanszlosek/crossword-generator#2]
Needed: Small database of words and hints to use for testing code.

**Comment by phionabrie** [comment]
[crosswordlist.txt](https://github.com/alanszlosek/crossword-generator/files/300959/crosswordlist.txt)

**Comment by developer99** [comment]
We can probably use a memory data structure and not necessarily a database engine to store this information as discussed.

**Comment by phionabrie** [comment]
Sounds like a plan.
